name: just_listen
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  
  chat_bubbles: ^1.10.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.4.0
  firebase_core: ^4.11.0
  firebase_storage: ^13.4.3
  firebase_ui_auth: ^3.0.1
  firebase_ui_oauth_google: ^2.0.1
  google_sign_in: ^6.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  progress_bar_countdown: ^0.0.3
  record: ^7.1.0
  uuid: ^4.5.3  # for unique filenames
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
