// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDirWyCFmHnm6ymGb4eOemmRAg8ldAraEI',
    appId: '1:665039344443:web:27c5530d4060d5dd19dd1e',
    messagingSenderId: '665039344443',
    projectId: 'just-listen-7b7e1',
    authDomain: 'just-listen-7b7e1.firebaseapp.com',
    storageBucket: 'just-listen-7b7e1.firebasestorage.app',
    measurementId: 'G-7C7T0P3C44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr9fpteG1UcTMgbhOa8NphL_7UXTzg2xo',
    appId: '1:665039344443:android:ae178ebec203678519dd1e',
    messagingSenderId: '665039344443',
    projectId: 'just-listen-7b7e1',
    storageBucket: 'just-listen-7b7e1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDirWyCFmHnm6ymGb4eOemmRAg8ldAraEI',
    appId: '1:665039344443:web:dfb77f663a5a12d219dd1e',
    messagingSenderId: '665039344443',
    projectId: 'just-listen-7b7e1',
    authDomain: 'just-listen-7b7e1.firebaseapp.com',
    storageBucket: 'just-listen-7b7e1.firebasestorage.app',
    measurementId: 'G-QJ5C504QTH',
  );
}
